ДЗ 1
vovangy/2022-2-VK-EDU-FS-FRONTEND-V-MALENKO pull request #1
Opened 2022-10-06 19:34 UTC by vovangy

# Домашнее задание №1

Прошу @martinkomitsky проверить его

Что было сделано:
- Добавлены тесты
- Добавлены функции

2022-10-10 20:25 UTC, martinkomitsky requested changes
Удалить из реквеста папку `node_modules`, добавить ее в .`gitignore`

2022-10-20 08:12 UTC, martinkomitsky commented
@vovangy будут ли исправления? И где следующие ДЗ?

2022-10-20 23:11 UTC, vovangy commented
Домашнее задание №1
Прошу @martinkomitsky проверить его

Что было сделано:
Удалил из реквест папку node_modules и добавил ее в .gitignore
Буду исправляться

2022-10-21 10:23 UTC, martinkomitsky approved these changes
12

2022-10-21 10:23 UTC, merged